name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-11', 'macos-12', 'macos-13', 'macos-14']
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
    runs-on: ${{ matrix.os }}
    name: Specs - ${{ matrix.os }} with Ruby ${{ matrix.ruby-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        rubygems: default
    - name: Run specs
      run: bundle exec rake
