name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint targeting Ruby 2.6
    runs-on: "macos-latest"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4"
        bundler-cache: true
        rubygems: default
    - name: Run rubocop
      run: bundle exec rake rubocop
  legacy-build-and-run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-13", "macos-14", "macos-15"]
    runs-on: ${{ matrix.os }}
    name: Ruby (default) / ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install devtools
      run: sudo xcode-select --reset
      env:
        PATH: "/usr/bin:/bin"
    - name: Install dependencies
      run: bundle install
      env:
        PATH: "/usr/bin:/bin"
    - name: Compile extension
      run: bundle exec rake compile
      env:
        PATH: "/usr/bin:/bin"
        OBJR_BUILD_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
    - name: Run specs
      run: bundle exec rake spec
      env:
        PATH: "/usr/bin:/bin"
  build-and-run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-13", "macos-14", "macos-15"]
        ruby-version: ["3.2", "3.3", "3.4"]
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby-version }} / ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        rubygems: default
    - name: Compile extension
      run: bundle exec rake compile
      env:
        OBJR_BUILD_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
    - name: Run specs
      run: bundle exec rake spec
