name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-11", "macos-12", "macos-13", "macos-14"]
        ruby-version: ["2.7", "3.0", "3.1", "3.2", "3.3"]
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby-version }} / ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        rubygems: default
    - name: Compile extension
      run: bundle exec rake compile
      env:
        OBJR_BUILD_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
    - name: Run specs
      run: bundle exec rake spec
  lint:
    name: Lint targeting Ruby 2.7
    runs-on: "macos-latest"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true
        rubygems: default
    - name: Run standard
      run: bundle exec rake standard
